AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 15
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  sendOtp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: sendOtp
      CodeUri: s3://ration-pro-qa/ab9340d49a29736e9ccea292488f7890
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        sendOtp:
          Type: Api
          Properties:
            Path: /user/sendOtp
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
