AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 3
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  editCategory:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: editCategory
      CodeUri: s3://ration-pro-qa/2338d7fafbba83a83cf85ee6b80c5d80
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        editCategory:
          Type: Api
          Properties:
            Path: /admin/editCategory
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
