AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 10
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  uploadProfilePicture:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: uploadProfilePicture
      CodeUri: s3://ration-pro-qa/cba52ed76e8dab23e9d94653c4d70eb7
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        uploadProfilePicture:
          Type: Api
          Properties:
            Path: /admin/uploadProfilePicture
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
