AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 3
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  sendOtp:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: verifyOtp
      CodeUri: s3://ration-pro-qa/3c8b2345e31cb5e79c4042f951ac5e25
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        verifyOtp:
          Type: Api
          Properties:
            Path: /user/verifyOtp
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
