AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 5
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  editOrder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: editOrder
      CodeUri: s3://ration-pro-qa/d5dd6725fd08466d051665ed8c64eb7f
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        editOrder:
          Type: Api
          Properties:
            Path: /admin/editOrder
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
