AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Ration Pro
  Sample SAM Template for Ration Pro

Globals:
  Function:
    Timeout: 3

Resources:
  ApiGatewayApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Prod
        Cors:
          AllowMethods: "'POST, GET, OPTIONS'"
          AllowHeaders: "'*'"
          AllowOrigin: "'*'"
          MaxAge: "'600'"
          AllowCredentials: false

  viewProfile: # Edit here
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: viewProfile #Edit here
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        viewProfile: #Edit here
          Type: Api
          Properties:
            Path: /user/viewProfile #Edit here
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
