AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 3
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  addCategory:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: addCategory
      CodeUri: s3://ration-pro-qa/9e15895e81b324b2c544300ffa774b50
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        addCategory:
          Type: Api
          Properties:
            Path: /admin/addCategory
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
