AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 5
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  viewallOrder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: viewallOrder
      CodeUri: s3://ration-pro-qa/f4154d8424de96711571d1619c1f12f5
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        viewallOrder:
          Type: Api
          Properties:
            Path: /admin/viewallOrder
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
