AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 10
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  viewrUserOrder:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: viewrUserOrder
      CodeUri: s3://ration-pro-qa/4c6ad440d15e17488c323e3bfe2abedb
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        viewrUserOrder:
          Type: Api
          Properties:
            Path: /admin/viewrUserOrder
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
