AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 10
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  uploadFilesCategory:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: uploadFilesCategory
      CodeUri: s3://ration-pro-qa/28829c9c8a17265ab9b285a5b00b387a
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        uploadFilesCategory:
          Type: Api
          Properties:
            Path: /admin/uploadFilesCategory
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
