AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 5
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  totalSales:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: totalSales
      CodeUri: s3://ration-pro-qa/8987f2b64638722e5f881937b171a43b
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        totalSales:
          Type: Api
          Properties:
            Path: /admin/totalSales
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
