AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 20
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  verifyPayment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: verifyPayment
      CodeUri: s3://ration-pro-qa/e6562cbbe172d4c2cc79d6a1f68bbc5d
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        verifyPayment:
          Type: Api
          Properties:
            Path: /user/verifyPayment
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
