AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'Ration Pro Sample SAM Template for Ration Pro

  '
Globals:
  Function:
    Timeout: 3
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors:
        AllowMethods: '''POST, GET, OPTIONS'''
        AllowHeaders: '''*'''
        AllowOrigin: '''*'''
        MaxAge: '''600'''
        AllowCredentials: false
  getNotification:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getNotification
      CodeUri: s3://ration-pro-qa/e1f4f0616dc2af5a5437bf7550777af2
      Handler: app.lambda_handler
      Runtime: python3.9
      Events:
        getNotification:
          Type: Api
          Properties:
            Path: /user/getNotification
            Method: post
            RestApiId:
              Ref: ApiGatewayApi
      Role: arn:aws:iam::568788240773:role/dev-admin
